run:
  timeout: 5m
  skip-dirs:
    - vendor
    - node_modules
    - web/node_modules
    - web/e2e/node_modules

linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign

linters-settings:
  gofmt:
    simplify: true
EOF < /dev/null