#!/usr/bin/env python3
#!/usr/bin/env python3
# Generated by Grimoire compiler
# Magic circle visual programming language

import sys
from concurrent.futures import ThreadPoolExecutor, as_completed

def main():
    print("Hello, World!")

if __name__ == '__main__':
    main()
