const { test, expect } = require('@playwright/test');

test.describe('WASM Integration Tests', () => {
  test.beforeEach(async ({ page }) => {
    await page.goto('/');
    // Wait for WASM to be fully initialized
    await page.waitForFunction(() => {
      return window.wasmInstance !== undefined && 
             window.processGrimoireImage !== undefined;
    }, { timeout: 30000 });
  });

  test('should detect symbols correctly', async ({ page }) => {
    // Test by calling WASM function directly
    const result = await page.evaluate(async () => {
      // Create a simple test image (base64 encoded 1x1 white pixel PNG)
      const testImageBase64 = 'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8/5+hHgAHggJ/PchI7wAAAABJRU5ErkJggg==';
      
      // Call the WASM function
      return window.processGrimoireImage(testImageBase64);
    });

    expect(result).toBeDefined();
    expect(result.success).toBeDefined();
    expect(result.code).toBeDefined();
  });

  test('should handle errors gracefully', async ({ page }) => {
    const result = await page.evaluate(async () => {
      // Invalid base64 data
      return window.processGrimoireImage('invalid-base64');
    });

    expect(result).toBeDefined();
    expect(result.success).toBe(false);
    expect(result.error).toBeDefined();
  });

  test('should return debug information', async ({ page }) => {
    // Click on a sample image
    await page.click('[data-sample="hello-world"]');
    await page.click('#execute-btn');
    
    // Wait for result
    await page.waitForSelector('.result-section', { state: 'visible' });
    
    // Switch to AST tab to see debug info
    await page.click('[data-tab="ast"]');
    
    // Get the result from the page
    const astContent = await page.textContent('#ast-content');
    expect(astContent).toBeTruthy();
    // Just check that some content exists
    expect(astContent.length).toBeGreaterThan(0);
  });

  test('should process all sample images without error', async ({ page }) => {
    const samples = ['hello-world', 'calculator', 'fibonacci', 'loop'];
    
    for (const sample of samples) {
      // Click on sample
      await page.click(`[data-sample="${sample}"]`);
      
      // Execute
      await page.click('#execute-btn');
      
      // Wait for result
      await page.waitForSelector('.result-section', { state: 'visible' });
      
      // Check no error is shown
      const errorSectionVisible = await page.isVisible('.error-section');
      expect(errorSectionVisible).toBe(false);
      
      // Check code was generated
      const codeContent = await page.textContent('#code-content');
      expect(codeContent).toContain('#!/usr/bin/env python3');
      
      // Clear for next test
      await page.reload();
      await page.waitForFunction(() => {
        return window.wasmInstance !== undefined;
      });
    }
  });

  test('should handle star symbols correctly', async ({ page }) => {
    await page.click('[data-sample="hello-world"]');
    await page.click('#execute-btn');
    
    await page.waitForSelector('.result-section', { state: 'visible' });
    
    // Check if Python code was generated
    const codeContent = await page.textContent('#code-content');
    expect(codeContent).toBeTruthy();
    expect(codeContent).toContain('#!/usr/bin/env python3');
  });

  test('should handle double circle symbols correctly', async ({ page }) => {
    await page.click('[data-sample="hello-world"]');
    await page.click('#execute-btn');
    
    await page.waitForSelector('.result-section', { state: 'visible' });
    
    // Check if code was generated
    const codeContent = await page.textContent('#code-content');
    expect(codeContent).toBeTruthy();
    expect(codeContent).toContain('# Generated by Grimoire');
  });
});