name: Simple Build Test

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-simple:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install system dependencies (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y libgl1

    - name: Install package
      run: |
        python -m pip install --upgrade pip wheel setuptools
        pip install -e .

    - name: Test imports
      run: |
        python -c "import grimoire; print('Import test passed')"
        python -c "from grimoire.cli import main; print('CLI import test passed')"
        python -c "from grimoire.compiler import GrimoireCompiler; print('Compiler import test passed')"

    - name: Test CLI
      run: |
        grimoire --help
        
    - name: Create simple executable (Unix)
      if: matrix.os != 'windows-latest'
      run: |
        mkdir -p dist
        echo '#!/usr/bin/env python3' > dist/grimoire
        echo 'import sys' >> dist/grimoire
        echo 'from grimoire.cli import main' >> dist/grimoire
        echo 'if __name__ == "__main__":' >> dist/grimoire
        echo '    sys.exit(main())' >> dist/grimoire
        chmod +x dist/grimoire
        ./dist/grimoire --help

    - name: Create simple executable (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        mkdir dist
        echo '@echo off' > dist/grimoire.bat
        echo 'python -m grimoire.cli %*' >> dist/grimoire.bat
        ./dist/grimoire.bat --help